name: Provision resources to aws

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
      run_apply:
        description: 'Apply after plan'
        required: true
        default: 'no'
        type: choice
        options:
          - 'yes'
          - 'no'

env:
  DEPLOY_ENV: ${{ github.event.inputs.environment || 'dev' }}
  RUN_APPLY : ${{ github.event.inputs.run_apply || 'no' }}
  AWS_REGION: ${{ vars.AWS_REGION }}
  ROLE_ARN: ${{ secrets.AWS_GITHUB_ACTIONS_ROLE_ARN }}

permissions:
  id-token: write
  contents: read

jobs:
  plan:
    name: Provision resources to AWS
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment || 'dev' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          ref: ${{ github.ref_name }}
    
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@d0834ad3a60a024346910e522a81b0002bd37fea
        with:
          role-to-assume: ${{ env.ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}
          role-session-name: gh-infra

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.14.4
      
      - name: Verify AWS Access
        run: |
          echo "Verifying AWS access..."
          aws sts get-caller-identity
          ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
          echo "Account ID: $ACCOUNT_ID"
      
      
      
